urls.py
# -*- coding: utf-8 -*-

from django.conf.urls.defaults import patterns

urlpatterns = patterns(
    'apps.pythia.views',
    (r'^login/$', 'login'),
    (r'^login/email/(?P<email>[^\/]+)/token/(?P<token>\w+)/$', 'login_link'),
    (r'^first/', 'first'),
    (r'^find_teacher/', 'find_teacher'),
    (r'^wizard/', 'wizard'),
    (r'^last/', 'last'),
    (r'^logout/', 'logout'),
    
    #(r'^count/(?P<letter>\w)/$', 'count'),
    (r'^stats/$', 'stats'),
    (r'^stats_question/(?P<question_id>\d+)/$', 'stats_question'),
    (r'^results/$', 'result_polls'),
    (r'^results/(?P<poll_id>\d+)/$', 'result_poll_teacherlist'),
    (r'^results/(?P<poll_id>\d+)/(?P<teacher_id>\d+)$', 'result_poll'),
    (r'^results_print/(?P<poll_id>\d+)/(?P<teacher_id>\d+)$', 'result_poll_print'),
    (r'^results/(?P<poll_id>\d+)/(?P<teacher_id>\d+)/(?P<subject_id>\d+)$', 'result_poll'),
    (r'^results/(?P<poll_id>\d+)/$', 'result_poll_teacherlist'),
    (r'^groupresults/(?P<poll_id>\d+)/(?P<department_id>\d+)$', 'result_poll_department'),
    (r'^groupresults/(?P<poll_id>\d+)/(?P<department_id>\d+)/(?P<mode>\w+)$', 'result_poll_department'),
    #(r'^$', 'index'),
)

models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MinLengthValidator
from django.utils.translation import ugettext_lazy as _
from apps.megacity.models import Student

from apps.syjon.lib.validators import validate_white_space
from apps.trainman.models import Teacher
from apps.merovingian.models import Subject, Course



class AbstractUniqueName(models.Model):
    class Meta:
        abstract = True
        ordering = ('name',)
        verbose_name = _(u'Name')
        verbose_name_plural = _(u'Names')

    name = models.CharField(max_length = 256,
                            unique = True,
                            verbose_name = _(u'name'),
                            validators = [MinLengthValidator(2), validate_white_space])

    def __unicode__(self):
        return unicode(self.name)

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        super(AbstractUniqueName, self).save(*args, **kwargs)

class AbstractName(models.Model):
    class Meta:
        abstract = True
        ordering = ('name',)
        verbose_name = _(u'Name')
        verbose_name_plural = _(u'Names')

    name = models.CharField(max_length = 256,
                            verbose_name = _(u'name'),
                            validators = [MinLengthValidator(2), validate_white_space])

    def __unicode__(self):
        return unicode(self.name)

    def save(self, *args, **kwargs):
        self.name = self.name.strip()
        super(AbstractName, self).save(*args, **kwargs)

class AbstractActive(AbstractUniqueName):
    class Meta:
        abstract = True
        ordering = ('-is_active', 'name')
        verbose_name = _(u'Name, active')
        verbose_name_plural = _(u'Names, active')
        
    is_active = models.BooleanField(db_column = 'is_active',
                                    default = True,
                                    verbose_name = _(u'Active'))
    
    def __unicode__(self):
        return '%s, %s' % (unicode(self.name), unicode(self.is_active))

    def set_active(self, active):
        self.is_active = active
        self.save()

class Poll(AbstractActive):
    class Meta:
        db_table = 'pythia_poll'
        verbose_name = _(u'Poll')
        verbose_name_plural = _(u'Polls')

    start_date = models.DateField(db_column = 'start_date',
                                  verbose_name = _(u'Start date'))
    end_date = models.DateField(db_column = 'end_date',
                                verbose_name = _(u'End date'))

    def __unicode__(self):
        s = unicode(self.name)
        if self.is_active:
            s += ' (A)'
        s += ' (%s - %s)' % (unicode(self.start_date), unicode(self.end_date))
        return s

    def save(self, *args, **kwargs):
        if self.is_active:
            for d in Poll.objects.filter(is_active = True):
                d.set_active(False)
        super(Poll, self).save(*args, **kwargs)

class CourseProperties(models.Model):
    class Meta:
        db_table = 'pythia_course_properties'
        verbose_name = _(u'Course properties')
        verbose_name_plural = _(u'Course properties')

    course = models.ForeignKey('merovingian.Course',
                              db_column = 'id_course',
                              verbose_name = _(u'Course'))
    semester = models.IntegerField(db_column = 'semester',
                                   max_length = 2,
                                   verbose_name = _(u'Semester'))
    token_number = models.IntegerField(db_column = 'token_number',
                                       verbose_name = _(u'Number of tokens'))

    def __unicode__(self):
        return '%s - %s : %s' % (unicode(self.course), self.semester, self.token_number)

class Token(AbstractActive):
    class Meta:
        db_table = 'pythia_token'
        verbose_name = _(u'Token')
        verbose_name_plural = _(u'Tokens')

    date = models.DateTimeField(db_column = 'date', null=True, blank=True,
                                verbose_name = _(u'Fill in date'))
    semester = models.IntegerField(db_column = 'semester',
                                   max_length = 2,
                                   verbose_name = _(u'Semester'))
    course = models.ForeignKey('merovingian.Course',
                              db_column = 'id_course',
                              verbose_name = _(u'Course'))
    poll = models.ForeignKey('Poll',
                             db_column = 'id_poll',
                             verbose_name = _(u'Poll'))
    student = models.ForeignKey(Student, verbose_name=_(u'Student'),
                                blank=True, null=True)
    sent = models.BooleanField(verbose_name=_(u'Sent'), default=False)

    def __unicode__(self):
        return '%s, %s, %s' % (self.name, self.course, self.semester)

QUESTION_TYPE_GROUP = 1
QUESTION_TYPE_GROUP_DESCRIPTION = 2
QUESTION_TYPE_CLOSEDEND_EVALUATION = 3
QUESTION_TYPE_CLOSEDEND_FINAL = 4
QUESTION_TYPE_OPEN_EVALUATION = 5
QUESTION_TYPE_OPEN_FINAL = 6

RESULT_ALLOWED_LIST = [1,2,3,4,5,6,7]

class QuestionType(AbstractName):
    class Meta:
        db_table = 'pythia_question_type'
        verbose_name = _(u'Question type')
        verbose_name_plural = _(u'Question types')

class Question(AbstractName):
    class Meta:
        db_table = 'pythia_question'
        ordering = ('sequence',)
        verbose_name = _(u'Question')
        verbose_name_plural = _(u'Questions')

    sequence = models.IntegerField(db_column = 'sequence',
                                   verbose_name = _(u'Sequence'))
    type = models.ForeignKey('QuestionType',
                             db_column = 'id_type',
                             verbose_name = _(u'Type'))
    poll = models.ForeignKey('Poll',
                             db_column = 'id_poll',
                             verbose_name = _(u'Poll'))
    weight = models.FloatField(db_column = 'weight',
                                 verbose_name = _(u'Weight'))

    def __unicode__(self):
        return unicode(self.name)

class AbstractTokenAnswer(models.Model):
    class Meta:
        abstract = True
        ordering = ('token',)
        verbose_name = _(u'Answer')
        verbose_name_plural = _(u'Answers')

    token = models.ForeignKey('Token',
                              db_column = 'id_token',
                              verbose_name = _(u'Token'))
    question = models.ForeignKey('Question',
                                 db_column = 'id_question',
                                 verbose_name = _(u'Question'))
    subject = models.ForeignKey('merovingian.Subject',
                                db_column = 'id_subject',
                                null = True,
                                blank = True,
                                verbose_name = _(u'Subject'))
    teacher = models.ForeignKey('trainman.Teacher',
                                db_column = 'id_teacher',
                                null = True,
                                blank = True,
                                verbose_name = _(u'Teacher'))

    def __unicode__(self):
        return '%s - %s - %s - %s' % (self.token.name, self.subject, self.teacher, self.question)

class Answer(AbstractName):
    class Meta:
        db_table = 'pythia_answer'
        ordering = ('sequence',)
        verbose_name = _(u'Answer')
        verbose_name_plural = _(u'Answers')

    sequence = models.IntegerField(db_column = 'sequence',
                                   verbose_name = _(u'Sequence'))
    weight = models.FloatField(db_column = 'weight',
                                 verbose_name = _(u'Weight'))
    question = models.ForeignKey('Question',
                                 db_column = 'id_question',
                                 verbose_name = _(u'Question'))
    mark = models.FloatField(db_column = 'mark',
                             verbose_name = _(u'Mark'))

class TokenAnswer(AbstractTokenAnswer):
    class Meta:
        db_table = 'pythia_token_answer'
        verbose_name = _(u'Closed-end answer')
        verbose_name_plural = _(u'Closed-end answers')

    answer = models.ForeignKey('Answer',
                               db_column = 'id_answer',
                               verbose_name = _(u'Answer'))

    def __unicode__(self):
        return super(TokenAnswer, self).__unicode__() + ' - ' + unicode(self.answer)

class TokenText(AbstractTokenAnswer):
    class Meta:
        db_table = 'pythia_token_text'
        verbose_name = _(u'Open answer')
        verbose_name_plural = _(u'Open answers')

    text = models.CharField(db_column = 'text',
                            max_length = 2048,
                            verbose_name = _(u'Answers'))

    def __unicode__(self):
        return super(TokenText, self).__unicode__() + ' - ' + unicode(self.text)
    
class ResultTeacher(models.Model):
    """
    Summary result for teacher
    """
    class Meta:
        db_table ='pythia_result_teacher'
        verbose_name = _(u'Poll result')
        verbose_name_plural = _(u'Poll results')
        
    teacher=models.ForeignKey(Teacher,db_column = 'id_teacher',verbose_name = _(u'Teacher'))
    votes  =models.IntegerField(db_column = 'votes', verbose_name = _(u'Votes'))
    mark   =models.FloatField(db_column = 'mark' , verbose_name = _(u'Mark' ))
    poll   =models.ForeignKey('Poll',db_column = 'id_poll',verbose_name = _(u'Poll'))
    
class ResultTeacherSubjectCourse(models.Model):
    """
    Summary result for one subject conducted by particular teacher 
    """
    class Meta:
        db_table ='pythia_result_teacher_subject_course'
        verbose_name = _(u'Poll result')
        verbose_name_plural = _(u'Poll results')
        
    teacher = models.ForeignKey(Teacher,db_column = 'id_teacher',verbose_name = _(u'Teacher'))
    subject = models.ForeignKey(Subject,db_column = 'id_subject',verbose_name = _(u'Subject'))

templates/pythia/base.html
{% extends "column_1.html" %}

{% load i18n %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}pythia/css/style.css" type="text/css" />
{% endblock %}

{% block page_title %}
{{ block.super }}
| {% trans "Course evaluation survey" %}
{% endblock %}

{% block breadcrumb %}

{% endblock %}

{% block horizontal_menu_items %}
{% comment %}
{% if perms.pythia.change_courseproperties %} 
<li><a href="{% url apps.pythia.views.index %}">{% trans "Number of students" %}</a></li>
{% endif %}
{% endcomment %}
{% if perms.pythia.change_courseproperties %}
<li><a href="{% url apps.pythia.views.stats %}">{% trans "Statistics" %}</a></li>
{% endif %}
{% endblock %}

{% block content %}

{% endblock %}

{% block footer_version %}
Pythia {{ VERSION_PYTHIA }}
{% endblock %}

templates/pythia/base_print.html
{% extends "base_0.html" %}

{% load i18n %}

{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{{ STATIC_URL }}pythia/css/style.css" type="text/css" />
{% endblock %}


{% block body %}
{% block content %}

{% endblock %}
{% endblock %}

templates/pythia/count.html
{% extends "pythia/base.html" %}

{% load i18n %}

{% block content %}

<div>
  	<h2>{% trans "Enter the numbers of students for following courses" %}</h2>
	
	<form action="" method="post">
	{% csrf_token %}
		
	<table class="table_0">
      	<thead><tr>
          	<td class="left label">{% trans "Courses" %} \ {% trans "Semesters" %}</td>
          	{% for i in semesters %}
          	<td class="left label">{{i}}</td>
          	{% endfor %}
    	</tr></thead>
      	
      	<tbody>
      		
		    {{ courses_students_number_formset.management_form }}
      		{% for form in courses_students_number_formset %}
		        <tr>
		        	<td class="left question">{{ form.course }}{{ form.course.label }}</td>
		        	{% for sem in semesters %}
		        		<td class="left label">
			          	{% for field in form.visible_fields %}
			          		{% if field.name == sem|stringformat:"d" %}
			          		{{ field }}
			          		{{ field.errors }}
			          		{%endif%}
			          	{% endfor %}
			          	</td>
		          	{% endfor %}
		        </tr>
		
		    {% endfor %}
      		
      	</tbody>
      	<thead><tr>
          	<td class="left label" colspan="11"><button type="submit">{% trans "Save" %}</button></td>
    	</tr></thead>
	</table>      	
		
	</form>

</div>

{% endblock %}

templates/pythia/last.html
{% extends "pythia/base.html" %}

{% load i18n %}

{% block content %}

<div id="last">
  <form action="{% url apps.pythia.views.last %}" method="post">
    {% csrf_token %}

    
    <table class="table_0">
      <thead>
        <tr>
          <td class="left label" colspan="2">{% trans "Final questions" %}</td>
        </tr>
      </thead>
      <tbody>
	    {% for formset in question_formset %}
	    {{ formset.management_form }}
	    {% if formset.forms %}
	        {% for form in formset.forms %}
	        <tr>
	          <td class="left question">{{ form.id }} {{ form.question }} {{ form.answer.label }}</td>
	          <td>{{ form.answer.errors }} {{ form.answer }}</td>
	        </tr>
	        {% endfor %}
	    {% endif %}
	    {% endfor %}
      </tbody>
    </table>

    <div class="spacer_10"></div>

    <div class="bar_0">
      <button class="button_2" type="submit" name="action" value="prev">{% trans "Go back to previous step" %}</button>
      <button class="button_2" type="submit" name="action" value="next">{% trans "Go to the next step" %}</button>
    </div>
  </form>
</div>

{% endblock %}

templates/pythia/login.html
{% extends "pythia/base.html" %}

{% load i18n %}

{% block content %}

<div id="login">
  <h2>
  	{% blocktrans with poll.name as name %}
  	Welcome to Course Evaluation Survey - {{ name }}.
  	{% endblocktrans %}
  </h2>
  <h2>{% trans "Insert your token and choose subjects that you want to give opinions about." %}</h2>
  <br />
  
  <form action="{% url apps.pythia.views.login %}" method="post">
    {% csrf_token %}
    <table class="table_0">
      <thead>
	<tr>
	  <td class="left" colspan="2">{% trans "Login" %}</td>
	</tr>
      </thead>
      </thead>
      <tbody>
        <tr>
          <td class="label left">{% trans "Token" %}:</td>
          <td>{{ token_form.token }}</td>
        </tr>
        <tr>
          <td class="label left">{% trans "E-mail" %}:</td>
          <td>{{ token_form.email }}</td>
        </tr>
      </tbody>
    </table>

    <div class="spacer_10"></div>

    <div class="bar_0">
      <button class="button_2" type="submit" name="action" value="login">{% trans "Log in" %}</button>
    </div>
  </form>
</div>

{% endblock %}

templates/pythia/logout.html
{% extends "pythia/base.html" %}

{% load i18n %}

{% block content %}

<div id="logout">
  <h2>
    {% trans "Thank you for your opinions." %}
  </h2>
  <p>
  	{% trans "The results will be given to the authorities of the University, deans of Faculties and teachers whose classes you have given opinions about." %}
  </p>
  <p>
  	{% trans "This gives you a real impact on the quality of education in the UMCS." %}
  </p>
</div>

{% endblock %}

templates/pythia/result_department.html
{% extends "pythia/base.html" %}

{% load i18n pythia_utils %}

{% block content %}

<div id="result_polls">
  <h2>
    {% blocktrans with poll_name=poll.name %}Poll results: {{ poll_name }}{% endblocktrans %}
  </h2>
  <hr style=" border: 0px; border-top: solid 1px #CCCCCC;"/>
  <h2>
    {% trans "Department:" %} {{department}} 

  </h2>
	
    <table class="table_0">
    <thead>
      <tr>
      	<td>{% trans "Page" %}</td>
      	<td class="td_answer_header">{% trans "Votes" %}</td>
      	<td class="td_answer_header">{% trans "Mark" %}</td>
      	
      </tr>
    </thead>
    <tbody>
    	<tr>
    		<td colspan="3"><a href="{% url apps.pythia.views.result_poll_department poll_id=poll.id department_id=department.id mode='detailed' %}" class="link_0">{% trans "Results table" %}</a></td>
    	</tr>
    	<tr>
    		<td colspan="3"><a href="{% url apps.pythia.views.result_poll_department poll_id=poll.id department_id=department.id mode='personal' %}" class="link_0">{% trans "Personal ranking" %}</a></td>
    	</tr>
    	<tr>
    		<td colspan="3"><a href="{% url apps.pythia.views.result_poll_department poll_id=poll.id department_id=department.id mode='department' %}" class="link_0">{% trans "Department ranking" %}</a></td>
    	</tr>
    	<tr>
    		<td colspan="3"><!-- <a href="{% url apps.pythia.views.result_poll_department poll_id=poll.id department_id=department.id mode='student' %}" class="link_0"> -->{% trans "Students' participation" %}<!-- </a> --></td>
    	</tr>
    	<tr class="td_summary">
    		<td colspan="1" ><a href="{% url apps.pythia.views.result_poll_department poll_id=poll.id department_id=department.id %}" class="link_0">{% trans "Summary" %}</a></td>
    		<td class="td_answer">{{ results.1 }}</td>
    		<td class="td_answer">{{ results.0 }}</td>
    	</tr>
    </tbody>
   </table>
   <div class="spacer_5"></div>
   {% if mode == "detailed" %}
	   {% for part in detailed_results.parts %}
			{% if part.type == 1 %}
				<div class="spacer_5"></div>
				<h3>{{ part.content }}</h3>
		    {% elif part.type == 2 %}
				{{ part.content }}
				<div class="spacer_5"></div>
		    {% elif part.type == 3 %}
		        <table class="table_0 row_highlight">
	    		<thead>
	      			<tr>
				      	<td>{% trans "Question" %}</td>
				      	{% for answer in part.answers %}
				      	<td class="td_answer_header">{{ answer }}</td>
				      	{% endfor %}
				      	<td class="td_answer_header">{% trans "Weight" %}</td>
				      	<td class="td_answer_header">{% trans "Mark" %}</td>
	      			</tr>
	    		</thead>
	    		<tbody>
	    			{% for question in part.questions %}
	    			<tr>
	    			<td>{{ question }}</td>
	    			{% for answer in part.answers %}
				    	<td class="td_answer">{{ question.answers|hash:answer }}</td>
				    {% endfor %}
				    <td class="td_answer">{{ question.weight_str }}%</td>
	    			<td class="td_answer">{{ question.mark_str }}</td>
	    			</tr>
	    			{% endfor %}
				</tbody>
				</table>
				<div class="spacer_5"></div>
			{% elif part.type == 4 %}
				<table class="table_0">
	    		<thead>
	    			<td class="td_comment_info"> {% trans "Teacher" %} </td>
	    			<td class="td_comment_info"> {% trans "Subject" %} </td>
	    			<td > {{ part.content }} </td>
	    			{% if is_superuser == 1 %}<td class="td_answer_header">{% trans "Student" %}</td>{% endif %}
	    		</thead>
	    		<tbody>
	    			{% for answer in part.answers %}
	    				<tr>
	    					<td>{{answer.teacher}}</td>
	    					<td>{{answer.subject}}</td>
	    					<td class="td_comment">{{answer.text}}</td>
	    					{% if is_superuser == 1 %}<td>{{answer.student}}</td>{% endif %}

	    				</tr>
	    			{% endfor %}
	    		</tbody>
	    		</table>
		    {% endif %}
	   {% endfor %}
   {% elif mode == "personal" %}
   <div class="spacer_5"></div>
   <table class="table_0 row_highlight">
	   <thead>
	      <tr>
	      	<td class="td_lp">{% trans "L.p." %}</td>
	      	<td>{% trans "Teacher" %}</td>
	      	<td class="td_answer_header">{% trans "Votes" %}</td>
	      	<td class="td_answer_header">{% trans "Mark" %}</td>
	      	
	      </tr>
	    </thead>
	    <tbody>
	    	{% for item in ranking %}
	    	<tr>
	    		<td>{{item.4}}</td>
		    	<td><a href="{% url apps.pythia.views.result_poll poll_id=poll.id teacher_id=item.0.id %}" class="link_0">{{ item.0 }}</a></td>
	    		<td class="td_answer">{{ item.1 }}</td>
	    		<td class="td_answer">{{ item.3 }}</td>
    		</tr>
	  	    {% endfor %}   	
	   </tbody>
   </table>
   {% elif mode == "department" %}
      <table class="table_0 row_highlight">
	   <thead>
	      <tr>
	      	<td class="td_lp">{% trans "L.p." %}</td>
	      	<td>{% trans "Unit" %}</td>
	      	<td class="td_answer_header">{% trans "Votes" %}</td>
	      	<td class="td_answer_header">{% trans "Marked" %}</td>
	      	<td class="td_answer_header">{% trans "Mark" %}</td>
	      	
	      </tr>
	    </thead>
	    <tbody>
	    	{% for item in ranking %}
	    	<tr>
	    		<td> {{item.5}}</td>
		    	<td><a href="{% url apps.pythia.views.result_poll_department poll_id=poll.id department_id=item.0.id mode='department' %}" class="link_0">{{ item.0 }}</a></td>
	    		<td class="td_answer">{{ item.1 }}</td>
	    		<td class="td_answer">{{ item.2 }}</td>
	    		<td class="td_answer">{{ item.4 }}</td>
    		</tr>
	  	    {% endfor %}   	
	   </tbody>
   </table>
   {% endif %}
   
</div>

{% endblock %}

templates/pythia/result_poll.html
{% extends "pythia/base.html" %}

{% load i18n pythia_utils %}

{% block content %}

<div id="result_polls">
  <h2>
    {% blocktrans with poll_name=poll.name %}Poll results: {{ poll_name }}{% endblocktrans %}
  </h2>
  <hr style=" border: 0px; border-top: solid 1px #CCCCCC;"/>
  <h2>
    {% trans "Teacher:" %} {{teacher.degree}} {{ teacher.user_profile.user.first_name }} {{ teacher.user_profile.second_name }} {{ teacher.user_profile.user.last_name }}
  </h2>
    <table class="table_0">
    <thead>
      <tr>
      	<td>{% trans "Subject" %}</td>
      	<td>{% trans "Course" %}</td>
      	<td class="td_answer_header">{% trans "Votes" %}</td>
      	<td class="td_answer_header">{% trans "Mark" %}</td>
      	
      </tr>
    </thead>
    <tbody>
    	
    	{% for subject in subjects %}
    	<tr>
    		<td><a href="{% url apps.pythia.views.result_poll poll_id=poll.id teacher_id=teacher.id subject_id=subject.subject.id %}" class="link_0">{{subject.subject}}</a></td>
    		<td>{{ subject.course }}</td>
    		<td class="td_answer">{{ subject.votes }}</td>
    		<td class="td_answer">{{ subject.mark_str }}</td>
    	</tr>
    	{% endfor %}
    	<tr class="td_summary">
    		<td colspan="2" ><a href="{% url apps.pythia.views.result_poll poll_id=poll.id teacher_id=teacher.id %}" class="link_0">{% trans "Summary" %}</a>
    			<a class="link_0" href="{% url apps.pythia.views.result_poll_print poll_id=poll.id teacher_id=teacher.id %}">(PDF)</a></td>
    		<td class="td_answer">{{ results.votes }}</td>
    		<td class="td_answer">{{ results.mark_str }}</td>
    	</tr>
    </tbody>
   </table>
   <div class="spacer_5"></div>
   {% if subject == None %}
   		<h2>{% trans "Summary" %}</h2>
   {% else %}
   		<h2>{{subject}}</h2>
   {% endif %}
   
   {% for part in detailedresults.parts %}
		
		{% if part.type == 1 %}
			<div class="spacer_5"></div>
			<h3>{{ part.content }}</h3>
	    {% elif part.type == 2 %}
			{{ part.content }}
			<div class="spacer_5"></div>
	    {% elif part.type == 3 %}
	        <table class="table_0 row_highlight">
    		<thead>
      			<tr>
			      	<td>{% trans "Question" %}</td>
			      	{% for answer in part.answers %}
			      	<td class="td_answer_header">{{ answer }}</td>
			      	{% endfor %}
			      	<td class="td_answer_header">{% trans "Weight" %}</td>
			      	<td class="td_answer_header">{% trans "Mark" %}</td>
      			</tr>
    		</thead>
    		<tbody>
    			{% for question in part.questions %}
    			<tr>
    			<td>{{ question }}</td>
    			{% for answer in part.answers %}
			    	<td class="td_answer">{{ question.answers|hash:answer }}</td>
			    {% endfor %}
			    <td class="td_answer">{{ question.weight_str }}%</td>
    			<td class="td_answer">{{ question.mark_str }}</td>
    			</tr>
    			{% endfor %}
			</tbody>
			</table>
			<div class="spacer_5"></div>
		{% elif part.type == 4 %}
			<table class="table_0">
    		<thead>
    			<td > {{ part.content }} </td>{% if is_superuser == 1 %}<td class="td_answer_header">{% trans "Student" %}</td>{% endif %}
    		</thead>
    		<tbody>
    			{% for answer in part.answers %}
    				<tr><td class="td_comment">{{answer.text}}</td>{% if is_superuser == 1 %}<td >{{answer.student}}</td>{% endif %}</tr>
    			{% endfor %}
    		</tbody>
    		</table>
	    {% endif %}
   {% endfor %}
</div>

{% endblock %}

templates/pythia/result_polls.html
{% extends "pythia/base.html" %}

{% load i18n %}

{% block content %}

<div id="result_polls">
  <h2>
    {% trans "Polls results" %}
  </h2>
  
<ul class="infolist">
<li>Szanowni Państwo, bardzo przepraszamy za błędy i utrudnienia pojawiające się na stronie związane z wynikami oceny zajęć na kontach indywidualnych. Średnie podane w obu semestrach były średnimi za cały rok 2012/2013, w dniu 14.03.2014 błąd został naprawiony. Aktualne średnie w każdym semestrze są średnimi tylko dla wybranego semestru.</li>
</ul>

  
  <p>{% trans "Check results of the finished polls shown in the table below." %}</p>
  <br />
	
  <table class="table_0">
    <thead>
      <tr>
      	<td>{% trans "Poll" %}</td>
      	<td class="td_poll_duration">{% trans "Expiry date" %}</td>
      </tr>
    </thead>
    <tbody>
    	{% for p in polls_page %}
    	<tr>
    		<td><a href="{% url apps.pythia.views.result_poll_teacherlist poll_id=p.id %}" class="link_0">{{ p.name }}</a></td>
    		<td>{{ p.start_date }} - {{ p.end_date }}</td>
    	</tr>
    	{% endfor %}
    </tbody>
   </table>
  
  {% load paginator %}
  {% paginator polls_page %}
</div>

{% endblock %}